name: ci-flutter

on:
  push:
    branches: [main]
    paths: ['packages/flutter/**']
  pull_request:
    paths: ['packages/flutter/**']

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/flutter
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: dart analyze lib/ test/
      - run: flutter test
