"""
仓储接口。消费方需实现此接口接入任意持久化后端。
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from quanttide_connect.models import Consensus, ConsensusStatus, Message, Relation


@runtime_checkable
class Repository(Protocol):
    """仓储接口。实现者可选用 SQLite、JSON、内存等后端。"""

    def add_message(self, msg: Message) -> Message: ...
    def get_message(self, message_id: str) -> Message | None: ...
    def list_messages(self) -> list[Message]: ...
    def update_message(self, message_id: str, new_content: str) -> Message | None: ...

    def add_consensus(self, c: Consensus) -> Consensus: ...
    def get_consensus(self, consensus_id: str) -> Consensus | None: ...
    def list_consensuses(
        self, status: ConsensusStatus | None = None
    ) -> list[Consensus]: ...
    def update_consensus_status(
        self, consensus_id: str, status: ConsensusStatus
    ) -> Consensus | None: ...

    def add_relation(self, r: Relation) -> Relation: ...
    def remove_relation(self, relation_id: str) -> bool: ...
    def get_relations_for_consensus(self, consensus_id: str) -> list[Relation]: ...
    def get_relations_for_message(self, message_id: str) -> list[Relation]: ...
