name: quanttide_docs
description: 量潮文档Dart SDK
version: 0.1.0
homepage: https://github.com/quanttide/quanttide-platform
repository: https://github.com/quanttide/quanttide-platform

environment:
  sdk: ^3.11.5

dependencies:
  bloc: ^9.0.0

dev_dependencies:
  test: ^1.25.0
